// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "S%QYn~7i,jHV0I5^f":
            case "Harry":return img`
. . . . . . f f f f . . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f f e f f e f f . . . . 
. . . f f e e e e e e f f . . . 
. . f f e e 4 e e 4 e e f f . . 
. . f f e 4 4 e e 4 4 e f f . . 
. . f e e 4 4 4 4 4 4 e e f . . 
. f f e 4 4 f 4 4 f 4 4 e f f . 
. f e 4 4 4 f 4 4 f 4 4 4 e f . 
. . f e e 4 4 2 2 4 4 e e f . . 
. . f f e e 4 4 4 4 e e f f . . 
. f f 4 f 7 7 7 7 7 7 f 4 f f . 
. f 4 d f 7 7 7 7 7 7 f d 4 f . 
. f 4 4 f 4 4 a a 4 4 f 4 4 f . 
. f f f f 6 6 6 6 6 6 f f f f . 
. . . . f 8 8 f f 8 8 f . . . . 
`;
            case "image2":
            case "Ghost0":return img`
........................
........................
......b3........bb......
......b.3......b.3......
.......b33ffffb33.......
........ffbb33ff........
.......fb113311bf.......
.......f111b3111f.......
......fd111b3111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image1":
            case "Ghost1":return img`
........................
........................
......b2........bb......
......b.2......b.2......
.......b22ffffb22.......
........ffbb22ff........
.......fb112211bf.......
.......f111b2111f.......
......fd111b2111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image6":
            case "Ghost5":return img`
........................
........................
......b7........bb......
......b.7......b.7......
.......b77ffffb77.......
........ffbb77ff........
.......fb117711bf.......
.......f111b7111f.......
......fd111b7111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image3":
            case "Ghost2":return img`
........................
........................
......b4........bb......
......b.4......b.4......
.......b44ffffb44.......
........ffbb44ff........
.......fb114411bf.......
.......f111b4111f.......
......fd111b4111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image4":
            case "Ghost3":return img`
........................
........................
......b5........bb......
......b.5......b.5......
.......b55ffffb55.......
........ffbb55ff........
.......fb115511bf.......
.......f111b5111f.......
......fd111b5111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image5":
            case "Ghost4":return img`
........................
........................
......b6........bb......
......b.6......b.6......
.......b66ffffb66.......
........ffbb66ff........
.......fb116611bf.......
.......f111b6111f.......
......fd111b6111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image7":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image8":
            case "Ghost6":return img`
........................
........................
......be........bb......
......b.e......b.e......
.......beeffffbee.......
........ffbbeeff........
.......fb11ee11bf.......
.......f111be111f.......
......fd111be111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image9":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image10":
            case "Ghost7":return img`
........................
........................
......bd........bb......
......b.d......b.d......
.......bddffffbdd.......
........ffbbddff........
.......fb11dd11bf.......
.......f111bd111f.......
......fd111bd111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image11":
            case "Ghost8":return img`
........................
........................
......bc........bb......
......b.c......b.c......
.......bccffffbcc.......
........ffbbccff........
.......fb11cc11bf.......
.......f111bc111f.......
......fd111bc111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image12":
            case "Ghost9":return img`
........................
........................
......bb........bb......
......b.b......b.b......
.......bbbffffbbb.......
........ffbbbbff........
.......fb11bb11bf.......
.......f111bb111f.......
......fd111bb111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image14":
            case "Ghost11":return img`
........................
........................
......ba........bb......
......b.a......b.a......
.......baaffffbaa.......
........ffbbaaff........
.......fb11aa11bf.......
.......f111ba111f.......
......fd111ba111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image13":
            case "Ghost10":return img`
........................
........................
......b9........bb......
......b.9......b.9......
.......b99ffffb99.......
........ffbb99ff........
.......fb119911bf.......
.......f111b9111f.......
......fd111b9111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image15":
            case "myImage1":return img`
........................
........................
........................
.......333....333.......
.......333....333.......
.........3ffff3.........
........ff3113ff........
.......fb113311bf.......
.....fffc1133111f.......
...fc111cd1331111f......
...f1b1b1b1111dddf......
...fbfbffcf11fcddf......
......fcf111111bbf......
.......ccbdb1b1fcf......
.......fffbfbfdff.......
........ffffffff........
........fffffffffff.....
.........fffffc111cf....
.........fffff1b1b1f....
..........ffffbfbfbf....
...........ffff.........
........................
........................
........................
`;
            case "image16":
            case "myImage2":return img`
........................
........................
........................
.......222....222.......
.......222....222.......
.........2ffff2.........
........ff2112ff........
.......fb112211bf.......
.....fffc1122111f.......
...fc111cd1221111f......
...f1b1b1b1111dddf......
...fbfbffcf11fcddf......
......fcf111111bbf......
.......ccbdb1b1fcf......
.......fffbfbfdff.......
........ffffffff........
........fffffffffff.....
.........fffffc111cf....
.........fffff1b1b1f....
..........ffffbfbfbf....
...........ffff.........
........................
........................
........................
`;
            case "image17":
            case "myImage3":return img`
........................
........................
........................
.......444....444.......
.......444....444.......
.........4ffff4.........
........ff4114ff........
.......fb114411bf.......
.....fffc1144111f.......
...fc111cd1441111f......
...f1b1b1b1111dddf......
...fbfbffcf11fcddf......
......fcf111111bbf......
.......ccbdb1b1fcf......
.......fffbfbfdff.......
........ffffffff........
........fffffffffff.....
.........fffffc111cf....
.........fffff1b1b1f....
..........ffffbfbfbf....
...........ffff.........
........................
........................
........................
`;
            case "image18":
            case "myImage4":return img`
........................
........................
........................
.......666....666.......
.......666....666.......
.........6ffff6.........
........ff6116ff........
.......fb116611bf.......
.....fffc1166111f.......
...fc111cd1661111f......
...f1b1b1b1111dddf......
...fbfbffcf11fcddf......
......fcf111111bbf......
.......ccbdb1b1fcf......
.......fffbfbfdff.......
........ffffffff........
........fffffffffff.....
.........fffffc111cf....
.........fffff1b1b1f....
..........ffffbfbfbf....
...........ffff.........
........................
........................
........................
`;
            case "image19":
            case "myImage5":return img`
........................
........................
........................
.......777....777.......
.......777....777.......
.........7ffff7.........
........ff7117ff........
.......fb117711bf.......
.....fffc1177111f.......
...fc111cd1771111f......
...f1b1b1b1111dddf......
...fbfbffcf11fcddf......
......fcf111111bbf......
.......ccbdb1b1fcf......
.......fffbfbfdff.......
........ffffffff........
........fffffffffff.....
.........fffffc111cf....
.........fffff1b1b1f....
..........ffffbfbfbf....
...........ffff.........
........................
........................
........................
`;
            case "image20":
            case "Harrison":return img`
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f f f c c f f f c . 
f f f c f f f f f f f c . 
c c c f f f e e f f c c . 
f f f f f e e f f c c f . 
f f f b f e e f b f f f . 
. f 4 1 f 4 4 f 1 4 f . . 
. f e 4 4 4 4 4 4 e f . . 
. f f f e e e e f f f . . 
f e f b 7 7 7 7 b f e f . 
e 4 f 7 7 7 7 7 7 f 4 e . 
e e f 6 6 6 6 6 6 f e e . 
. . . f f f f f f . . . . 
. . . f f . . f f . . . . 
`;
            case "image21":
            case "Harrison0":return img`
. . . . 1 1 1 1 . . . . . 
. . 1 1 1 1 1 1 1 1 . . . 
. 1 1 5 1 1 1 c 1 1 1 . . 
1 1 5 6 5 1 c c 1 1 1 c . 
1 1 1 5 1 1 1 1 1 1 5 c . 
c c c 1 1 1 4 4 1 5 6 5 . 
1 1 1 1 1 4 4 1 1 c 5 1 . 
1 1 1 b f 4 4 f b 1 1 1 . 
. f 4 1 f 4 4 f 1 4 f . . 
. f 4 4 4 4 4 4 4 4 f . . 
. f f f 3 7 7 3 f f f . . 
f 4 f 6 3 6 6 3 6 f 4 f . 
4 4 f 7 3 7 7 3 7 f 4 4 . 
4 4 f 6 3 6 6 3 6 f 4 4 . 
. . . f f f f f f . . . . 
. . . f f . . f f . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim1":
            case "anim3":return [img`
. . . . . f f f f f . . . 
. . . f f f f f f f f f . 
. . f f f c f f f f f f . 
. . f f c f f f c f f f f 
f f c c f f f c c f f c f 
f f f f f e f f f f c c f 
. f f f e e f f f f f f f 
. . f f e e f b f e e f f 
. . . f 4 4 f 1 e 4 e f . 
. . . f 4 4 4 4 e f f f . 
. . . f f e e e e e f . . 
. . . f 7 7 7 e 4 4 e . . 
. . . f 7 7 7 e 4 4 e . . 
. . . f 6 6 6 f e e f . . 
. . . . f f f f f f . . . 
. . . . . . f f f . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . f f f f f f . . . 
. . . f f f f f f f f f . 
. . f f f c f f f f f f . 
. f f f c f f f c f f f f 
f f c c f f f c c f f c f 
f f f f f e f f f f c c f 
. f f f e e f f f f f f f 
. . f f e e f b f e e f f 
. . f f 4 4 f 1 e 4 e f . 
. . . f 4 4 4 e e f f f . 
. . . f f e e 4 4 e f . . 
. . . f 7 7 e 4 4 e f . . 
. . f f 6 6 f e e f f f . 
. . f f f f f f f f f f . 
. . . f f f . . . f f . . 
`, img`
. . . . . . . . . . . . . 
. . . . f f f f f f . . . 
. . . f f f f f f f f f . 
. . f f f c f f f f f f . 
. f f f c f f f c f f f f 
f f c c f f f c c f f c f 
f f f f f e f f f f c c f 
. f f f e e f f f f f f f 
. f f f e e f b f e e f f 
. . f f 4 4 f 1 e 4 e f f 
. . . f 4 4 4 4 e f f f . 
. . . f f e e e e 4 4 4 . 
. . . f 7 7 7 7 e 4 4 e . 
. . f f 6 6 6 6 f e e f . 
. . f f f f f f f f f f . 
. . . f f f . . . f f . . 
`];
            case "myAnim2":
            case "anim4":return [img`
. . . . . . . . . . . . . 
. . . f f f f f f . . . . 
. f f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f c f f f c f f f . 
f c f f c c f f f c c f f 
f c c f f f f e f f f f f 
f f f f f f f e e f f f . 
f f e e f b f e e f f f . 
f f e 4 e 1 f 4 4 f f . . 
. f f f e 4 4 4 4 f . . . 
. 4 4 4 e e e e f f . . . 
. e 4 4 e 7 7 7 7 f . . . 
. f e e f 6 6 6 6 f f . . 
. f f f f f f f f f f . . 
. . f f . . . f f f . . . 
`, img`
. . . . . . . . . . . . . 
. . . f f f f f f . . . . 
. f f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f c f f f c f f f . 
f c f f c c f f f c c f f 
f c c f f f f e f f f f f 
f f f f f f f e e f f f . 
f f e e f b f e e f f . . 
. f e 4 e 1 f 4 4 f f . . 
. f f f e e 4 4 4 f . . . 
. . f e 4 4 e e f f . . . 
. . f e 4 4 e 7 7 f . . . 
. f f f e e f 6 6 f f . . 
. f f f f f f f f f f . . 
. . f f . . . f f f . . . 
`, img`
. . . f f f f f . . . . . 
. f f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f c f f f c f f . . 
f c f f c c f f f c c f f 
f c c f f f f e f f f f f 
f f f f f f f e e f f f . 
f f e e f b f e e f f . . 
. f e 4 e 1 f 4 4 f . . . 
. f f f e 4 4 4 4 f . . . 
. . f e e e e e f f . . . 
. . e 4 4 e 7 7 7 f . . . 
. . e 4 4 e 7 7 7 f . . . 
. . f e e f 6 6 6 f . . . 
. . . f f f f f f . . . . 
. . . . f f f . . . . . . 
`];
            case "myAnim":
            case "anim1":return [img`
. . . . f f f f . . . . . 
. . f f c c c c f f . . . 
. f f c c c c c c f f . . 
f f c c c c c c c c f f . 
f f c c f c c c c c c f . 
f f f f f c c c f c c f . 
f f f f c c c f c c f f . 
f f f f f f f f f f f f . 
f f f f f f f f f f f f . 
. f f f f f f f f f f . . 
. f f f f f f f f f f . . 
f e f f f f f f f f e f . 
e 4 f 7 7 7 7 7 7 c 4 e . 
e e f 6 6 6 6 6 6 f e e . 
. . . f f f f f f . . . . 
. . . f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . . f f f f . . . . 
. . . f f c c c c f f . . 
. f f f c c c c c c f f . 
f f c c c c c c c c c f f 
f c c c c f c c c c c c f 
. f f f f c c c c f c c f 
. f f f f c c f c c c f f 
. f f f f f f f f f f f f 
. f f f f f f f f f f f f 
. . f f f f f f f f f f . 
. . e f f f f f f f f f . 
. . e f f f f f f f f e f 
. . 4 c 7 7 7 7 7 e 4 4 e 
. . e f f f f f f f e e . 
. . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . . f f f f . . . . 
. . . f f c c c c f f . . 
. . f f c c c c c c f f . 
. f f f c c c c c c c f f 
f f f c c c c c c c c c f 
f f c c c f c c c c c c f 
. f f f f f c c c f c f f 
. f f f f c c f f c f f f 
. . f f f f f f f f f f f 
. . f f f f f f f f f f . 
. . f f f f f f f f f e . 
. f e f f f f f f f f e . 
. e 4 4 e 7 7 7 7 7 c 4 . 
. . e e f f f f f f f e . 
. . . . . . . . f f f . . 
`];
            case "myAnim0":
            case "anim2":return [img`
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f f f c c f f f c . 
f f f c f f f f f f f c . 
c c c f f f e e f f c c . 
f f f f f e e f f c c f . 
f f f b f e e f b f f f . 
. f 4 1 f 4 4 f 1 4 f . . 
. f e 4 4 4 4 4 4 e f . . 
. f f f e e e e f f f . . 
f e f b 7 7 7 7 b f e f . 
e 4 f 7 7 7 7 7 7 f 4 e . 
e e f 6 6 6 6 6 6 f e e . 
. . . f f f f f f . . . . 
. . . f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . . f f f f . . . . 
. . . f f f f f f f f . . 
. . f f f f f f c f f f . 
f f f f f f f c c f f f c 
f f f f c f f f f f f f c 
. c c c f f f e e f f c c 
. f f f f f e e f f c c f 
. f f f b f e e f b f f f 
. f f 4 1 f 4 4 f 1 4 f f 
. . f e 4 4 4 4 4 e e f e 
. f e f b 7 7 7 e 4 4 4 e 
. e 4 f 7 7 7 7 e 4 4 e . 
. . . f 6 6 6 6 6 e e . . 
. . . f f f f f f f . . . 
. . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f c f f f f f f . . 
c f f f c c f f f f f f f 
c f f f f f f f c f f f f 
c c f f e e f f f c c c . 
f c c f f e e f f f f f . 
f f f b f e e f b f f f . 
f f 4 1 f 4 4 f 1 4 f f . 
e f e e 4 4 4 4 4 e f . . 
e 4 4 4 e 7 7 7 b f e f . 
. e 4 4 e 7 7 7 7 f 4 e . 
. . e e 6 6 6 6 6 f . . . 
. . . f f f f f f f . . . 
. . . . . . . f f f . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
